CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';

CREATE DATABASE IF NOT EXISTS testeDB;

ALTER DATABASE testeDB
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON testeDB.* TO 'admin'@'%' IDENTIFIED BY 'admin';